import * as mupdf from "mupdf"; import sharp from "sharp"; import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path"; import { fileURLToPath } from "node:url";
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const env = {}; for (const l of readFileSync(resolve(ROOT, ".env.local"), "utf8").split(/\r?\n/)) { const m = l.match(/^([^#=]+)=(.*)$/); if (m) env[m[1].trim()] = m[2].trim(); }
const AKEY = env.ANTHROPIC_API_KEY; const sleep = ms => new Promise(r=>setTimeout(r,ms));
const SYS="You read printed area labels off Belgian floor-plan tiles. You ALSO read common circulation (traphal/hal/gemene delen/gaanderij) as cat1 if labelled. Return ONLY JSON.";
const INSTR=`These overlapping TILES are ONE floor-plan sheet. Read cat1 (heated living incl. common circulation), cat2, cat3.
cat1_basis: "gross"=BO/bruto; "net"=net floor INCLUDING common circulation (you summed dwellings AND traphal/hal/gemene delen); "unit_net"=ONLY dwelling units' netto area, circulation NOT labelled/included; "mixed".
Return JSON: {"cat1_m2":<n>,"cat1_basis":"gross|net|unit_net|mixed","circulation_labelled":<bool>,"note":"what you read incl whether traphal/hal had m²"}`;
async function tiles(file,p){const doc=mupdf.Document.openDocument(readFileSync(file),"application/pdf");const pix=doc.loadPage(p).toPixmap(mupdf.Matrix.scale(200/72,200/72),mupdf.ColorSpace.DeviceRGB,false,true);const full=Buffer.from(pix.asPNG());const W=pix.getWidth(),H=pix.getHeight(),G=3,OV=0.1,out=[];for(let gy=0;gy<G;gy++)for(let gx=0;gx<G;gx++){const left=Math.max(0,Math.floor((gx/G-OV)*W)),top=Math.max(0,Math.floor((gy/G-OV)*H));const w=Math.min(W-left,Math.ceil((1/G+2*OV)*W)),h=Math.min(H-top,Math.ceil((1/G+2*OV)*H));let png=await sharp(full).extract({left,top,width:w,height:h}).png().toBuffer();if(Math.max(w,h)>1600)png=await sharp(png).resize(w>=h?{width:1568}:{height:1568}).png().toBuffer();if(png.length<=3.7e6)out.push(png.toString("base64"));}return out;}
async function vision(imgs){await sleep(800);const content=[{type:"text",text:INSTR},...imgs.map(b=>({type:"image",source:{type:"base64",media_type:"image/png",data:b}}))];const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"x-api-key":AKEY,"anthropic-version":"2023-06-01","content-type":"application/json"},body:JSON.stringify({model:"claude-sonnet-4-6",max_tokens:1200,system:SYS,messages:[{role:"user",content}]})});const j=await res.json();if(!res.ok)throw new Error(JSON.stringify(j).slice(0,150));const m=(j.content?.[0]?.text||"").match(/\{[\s\S]*\}/);return m?JSON.parse(m[0]):null;}
const cases=[["23-499974 GVL","C:/Users/tieme/Desktop/testing 1_6/23-4999740plannen.pdf",1,"unit_net verwacht (alleen APP-labels)"],["HOOST L+02","C:/Users/tieme/Desktop/testing 30_5/25-5475630plannen.pdf",1,"net verwacht (incl gaanderij/traphal)"]];
for(const [name,file,p,exp] of cases){try{const r=await vision(await tiles(file,p));const f=r.cat1_basis==='unit_net'?1.35:(r.cat1_basis==='net'||r.cat1_basis==='room_net')?1.12:r.cat1_basis==='mixed'?1.06:1.0;console.log(`${name}: cat1_basis=${r.cat1_basis} circ_labelled=${r.circulation_labelled} → factor ×${f} (${exp})`);console.log(`   note: ${(r.note||'').slice(0,140)}`);}catch(e){console.log(`${name} FOUT ${String(e.message).slice(0,100)}`);}}
