import * as mupdf from "mupdf"; import sharp from "sharp"; import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path"; import { fileURLToPath } from "node:url";
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const env = {}; for (const l of readFileSync(resolve(ROOT, ".env.local"), "utf8").split(/\r?\n/)) { const m = l.match(/^([^#=]+)=(.*)$/); if (m) env[m[1].trim()] = m[2].trim(); }
const AKEY = env.ANTHROPIC_API_KEY; const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const FILE = "C:/Users/tieme/Desktop/testing 1_6/23-49997800plannen.pdf";
const doc = mupdf.Document.openDocument(readFileSync(FILE), "application/pdf");
async function tiles(p){const pix=doc.loadPage(p).toPixmap(mupdf.Matrix.scale(230/72,230/72),mupdf.ColorSpace.DeviceRGB,false,true);const full=Buffer.from(pix.asPNG());const W=pix.getWidth(),H=pix.getHeight(),G=3,OV=0.1,out=[];for(let gy=0;gy<G;gy++)for(let gx=0;gx<G;gx++){const left=Math.max(0,Math.floor((gx/G-OV)*W)),top=Math.max(0,Math.floor((gy/G-OV)*H));const w=Math.min(W-left,Math.ceil((1/G+2*OV)*W)),h=Math.min(H-top,Math.ceil((1/G+2*OV)*H));let png=await sharp(full).extract({left,top,width:w,height:h}).png().toBuffer();if(Math.max(w,h)>1600)png=await sharp(png).resize(w>=h?{width:1568}:{height:1568}).png().toBuffer();if(png.length<=3.7e6)out.push(png.toString("base64"));}return out;}
const SYS="You inspect ONE Belgian apartment floor-plan sheet (tiles). Report ONLY the common/shared spaces. Return ONLY JSON.";
const INSTR=`On this floor, list the COMMON / shared spaces (NOT private apartments): inkomhal, traphal, trappenhal, lifthal, lift, circulatie, gang, gemene delen, gemeenschappelijke ruimte, fietsenberging, technische ruimte. For each, give its label and whether an m² value is PRINTED next to it.
Return JSON: {"common_spaces":[{"label":"...","m2":<n or null>,"m2_printed":<bool>}],"any_common_m2_printed":<bool>,"note":"are common areas labelled with m², or only named/drawn?"}`;
async function vision(imgs){await sleep(800);const content=[{type:"text",text:INSTR},...imgs.map(b=>({type:"image",source:{type:"base64",media_type:"image/png",data:b}}))];const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"x-api-key":AKEY,"anthropic-version":"2023-06-01","content-type":"application/json"},body:JSON.stringify({model:"claude-sonnet-4-6",max_tokens:1500,system:SYS,messages:[{role:"user",content}]})});const j=await res.json();if(!res.ok)throw new Error(JSON.stringify(j).slice(0,150));const m=(j.content?.[0]?.text||"").match(/\{[\s\S]*\}/);return m?JSON.parse(m[0]):null;}
for(const [name,p] of [["Niveau 0",6],["Niveau +1",10]]){try{const r=await vision(await tiles(p));console.log(`${name}: any_printed=${r.any_common_m2_printed}`);console.log(`  note: ${(r.note||'').slice(0,160)}`);console.log(`  spaces: `+(r.common_spaces||[]).map(s=>`${s.label}${s.m2_printed?'='+s.m2+'m²':'(geen m²)'}`).join(", "));}catch(e){console.log(`${name} FOUT`,String(e.message).slice(0,90));}}
